version: "3.7"

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - GO_VERSION=1.12
    image: mrkaran/calert:1.0.0-stable
    ports:
      - "6000:6000"
    volumes:
      - '/Users/docker-data/:/etc/calert'
