apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
      - name: calert
        image: mrkaran/calert:1.0.0
        ports:
        - containerPort: 6000
        volumeMounts:
        - mountPath: /etc/calert/
          name: config-dir
      volumes:
        - name: config-dir
          configMap:
            name: app-config